### PR TITLE
feature: allow custom replace in escapeClassName (#25)

### PR DESCRIPTION
**Pull request by linuxuser586**
I found an issue where names can clash when renamed. I updated the code so that one may override or add to the default replace regex.

### CODE REVIEW

**Comment by linuxuser586** [comment]
@MartinKavik sorry about the reformatting noise. My IDE kept changing the format so I updated eslint to format all js files. That got rid of the noise on the files I touched, but inadvertently made format changes to other files.

**Comment by MartinKavik** [comment]
The code looks good on the first glance. 
I'm quite busy these days and I no longer use the library in my active projects because I focus on [MoonZoon](https://github.com/MoonZoon/MoonZoon) now with a Rust abstraction over CSS so I won't have time / motivation to test it manually by myself.
However I assume you are an experienced developer and the modified code works with your use case - can we merge it? (Then I'll release a new version.)
Btw where are you using the library? (I'm just curious, you don't have to answer if it's a private project.)

**Comment by linuxuser586** [comment]
@MartinKavik Please merge it. I am using the library and experimenting with Seed and so far like it very much. It's for a hobby project.

**Comment by MartinKavik** [comment]
Fixes https://github.com/MartinKavik/postcss-typed-css-classes/issues/25

**Comment by MartinKavik** [comment]
v0.2.5 released on github and npm.
@linuxuser586 Please update README when you have time so other people know how to use your new features.

**Comment by linuxuser586** [comment]
@MartinKavik done

**Pull request merged**
